---
- name: Transfer and execute a script.
  hosts: test
  user: centos
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=setup.sh dest=/home/centos mode=0777

     - name: Execute the script
       command: sh /home/centos/setup.sh
